-- Migration 040: Make fluxcore_cognition_queue.last_signal_seq nullable
--
-- Why: Allow the legacy messageCore path (and new MessageDispatchService gate)
-- to enqueue cognitive turns without a corresponding Journal signal.
-- The CognitionWorker and CognitiveDispatcher do not use lastSignalSeq
-- for history resolution — history is fetched from the messages table directly.
--
-- Safe: no data loss, no table rewrite. Only relaxes a constraint.

-- 1. Drop FK constraint (if exists — name generated by Postgres/Drizzle)
DO $$
DECLARE
    v_constraint text;
BEGIN
    SELECT tc.constraint_name
    INTO v_constraint
    FROM information_schema.table_constraints tc
    JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
    WHERE tc.table_name = 'fluxcore_cognition_queue'
        AND tc.constraint_type = 'FOREIGN KEY'
        AND kcu.column_name = 'last_signal_seq'
    LIMIT 1;

    IF v_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE fluxcore_cognition_queue DROP CONSTRAINT %I', v_constraint);
        RAISE NOTICE 'Dropped FK constraint: %', v_constraint;
    ELSE
        RAISE NOTICE 'No FK constraint found on last_signal_seq — skipping';
    END IF;
END $$;

-- 2. Make last_signal_seq nullable
ALTER TABLE fluxcore_cognition_queue
    ALTER COLUMN last_signal_seq DROP NOT NULL;

-- 3. Add unique partial index on conversation_id WHERE processed_at IS NULL
-- Required for onConflictDoUpdate(target: [conversationId]) to work correctly.
-- Partial: allows multiple processed entries for the same conversation (history).
CREATE UNIQUE INDEX IF NOT EXISTS ux_cognition_queue_pending_conversation
    ON fluxcore_cognition_queue (conversation_id)
    WHERE processed_at IS NULL;

-- Verify
DO $$
DECLARE
    is_nullable text;
BEGIN
    SELECT is_nullable INTO is_nullable
    FROM information_schema.columns
    WHERE table_name = 'fluxcore_cognition_queue'
        AND column_name = 'last_signal_seq';
    RAISE NOTICE 'last_signal_seq is_nullable: %', is_nullable;
END $$;
